language: go
go: 
 - 1.1
 - 1.2
 - 1.3
 - release
 - tip

before_install:
 - go get github.com/tools/godep
 - export PATH=$HOME/gopath/bin:$PATH

script:
 - godep go build

matrix:
  allow_failures:
    - go: tip
